# Generated by Django 5.2.7 on 2025-11-13 14:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('daily_reports', 'Daily Reports'), ('weekly_activity', 'Weekly Activity'), ('monthly_resolution', 'Monthly Resolution Rate'), ('user_registrations', 'User Registrations'), ('county_breakdown', 'County Breakdown')], max_length=50)),
                ('metric_value', models.JSONField(help_text='Stores metric data in JSON format')),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['metric_type', 'date_recorded'], name='Dashboard_d_metric__44d23f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'verbose_name_plural': 'System Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
