# Generated by Django 5.2.7 on 2025-10-18 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
        ('Location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_at_submission', models.CharField(help_text="Snapshot of the reporter's role when submitting (e.g. citizen).", max_length=32)),
                ('title', models.CharField(help_text='Short summary of the issue.', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of the issue.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude from GPS (auto-filled from Check My Location).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude from GPS (auto-filled from Check My Location).', max_digits=9, null=True)),
                ('verified_by_ai', models.BooleanField(default=False, help_text='True if the AI verified this report automatically.')),
                ('ai_confidence', models.FloatField(blank=True, help_text='Confidence score from AI model (0.0–1.0).', null=True)),
                ('image_required_passed', models.BooleanField(default=False, help_text='True if required image evidence was provided.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified (AI confirmed)'), ('pending', 'Pending (awaiting county review)'), ('noted', 'Noted (official has seen)'), ('on_progress', 'On Progress (being addressed)'), ('resolved', 'Resolved'), ('rejected', 'Rejected (invalid or duplicate)'), ('deleted', 'Deleted')], default='submitted', help_text='Current state of this report in the workflow.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='Location.county')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted the report (soft delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reports', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='County department responsible for this issue (auto-detected by AI).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='Departments.countydepartment')),
                ('reporter', models.ForeignKey(help_text='User who created this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='Location.subcounty')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='Location.ward')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Uploaded image (from camera or gallery).', upload_to='report_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional description for the image.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Report this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Reports.report')),
            ],
            options={
                'verbose_name': 'Report Image',
                'verbose_name_plural': 'Report Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
