# Generated by Django 5.2.7 on 2025-11-04 11:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Location', '0001_initial'),
        ('Reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Development Like',
                'verbose_name_plural': 'Development Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentDevelopment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the development project', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget allocated for this project', max_digits=12, null=True)),
                ('start_date', models.DateField(help_text='Project start date')),
                ('expected_completion', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('actual_completion', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Current progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_updates', models.TextField(blank=True, help_text='Regular updates on project progress')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Development',
                'verbose_name_plural': 'Government Developments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Like',
                'verbose_name_plural': 'Report Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Expected or actual completion date', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='development_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated for this development (if applicable)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='development_progress',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='report',
            name='government_response',
            field=models.TextField(blank=True, help_text='Official government response to this report', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_development_showcase',
            field=models.BooleanField(default=False, help_text='Mark as true if this report showcases government development work'),
        ),
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this report', related_name='liked_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='responded_by',
            field=models.ForeignKey(blank=True, help_text='Official who provided the response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='response_date',
            field=models.DateTimeField(blank=True, help_text='When the government responded', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='Reports_rep_status_e8b664_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['county', 'status'], name='Reports_rep_county__41d166_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['department', 'created_at'], name='Reports_rep_departm_0ea5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_development_showcase', 'created_at'], name='Reports_rep_is_deve_852a37_idx'),
        ),
        migrations.AddField(
            model_name='developmentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governmentdevelopment',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='Location.county'),
        ),
        migrations.AddField(
            model_name='governmentdevelopment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_developments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governmentdevelopment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='Departments.countydepartment'),
        ),
        migrations.AddField(
            model_name='governmentdevelopment',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Project images and progress photos', to='Reports.reportimage'),
        ),
        migrations.AddField(
            model_name='governmentdevelopment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_developments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentlike',
            name='development',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_instances', to='Reports.governmentdevelopment'),
        ),
        migrations.AddField(
            model_name='reportlike',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_instances', to='Reports.report'),
        ),
        migrations.AddField(
            model_name='reportlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='governmentdevelopment',
            index=models.Index(fields=['county', 'status'], name='Reports_gov_county__b54737_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentdevelopment',
            index=models.Index(fields=['department', 'created_at'], name='Reports_gov_departm_211efc_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentdevelopment',
            index=models.Index(fields=['status', 'expected_completion'], name='Reports_gov_status_4c8790_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='developmentlike',
            unique_together={('user', 'development')},
        ),
        migrations.AlterUniqueTogether(
            name='reportlike',
            unique_together={('user', 'report')},
        ),
    ]
