# Generated by Django 5.2.7 on 2025-11-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_developmentlike_governmentdevelopment_reportlike_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportlike',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='DevelopmentLike',
        ),
        migrations.DeleteModel(
            name='ReportLike',
        ),
    ]
