# Generated by Django 5.2.7 on 2025-11-19 07:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_alter_reportlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Uploaded image (from camera or gallery).', max_length=255, verbose_name='image'),
        ),
    ]
