# Generated by Django 5.2.7 on 2025-11-20 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Location', '0001_initial'),
        ('Reports', '0004_alter_reportimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anonymous_display_name',
            field=models.CharField(blank=True, default='Anonymous Citizen', help_text='Display name shown publicly for anonymous reports', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='True if reporter chose to remain anonymous publicly'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the report', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_anonymous', 'created_at'], name='Reports_rep_is_anon_6bfeb8_idx'),
        ),
    ]
