# Generated by Django 5.2.7 on 2025-11-26 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Location', '0001_initial'),
        ('Reports', '0005_report_anonymous_display_name_report_is_anonymous_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hide_reporter_info',
            field=models.BooleanField(default=False, help_text='Hide all reporter information from public view'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['priority', 'created_at'], name='Reports_rep_priorit_eadd51_idx'),
        ),
    ]
