# Generated by Django 5.2.7 on 2025-10-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='county',
            field=models.ForeignKey(blank=True, help_text='County where the user belongs or works.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Location.county'),
        ),
    ]
