# Generated by Django 5.2.7 on 2025-10-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customuser_county'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='county',
            field=models.ForeignKey(blank=True, help_text='County where the report belongs or works.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Location.county'),
        ),
    ]
