# Generated by Django 5.2.7 on 2025-10-18 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Physical office address', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_departments', to='Location.county')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_departments', to='Departments.department')),
            ],
            options={
                'verbose_name': 'County Department',
                'verbose_name_plural': 'County Departments',
                'ordering': ['county__name', 'department__name'],
                'unique_together': {('county', 'department')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='e.g. Chief Officer, Director', max_length=100, null=True)),
                ('is_head', models.BooleanField(default=False, help_text='Is this the head of the department?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='Departments.countydepartment')),
                ('user', models.ForeignKey(help_text='User linked to this official (must have role=county_official)', on_delete=django.db.models.deletion.CASCADE, related_name='department_officials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Official',
                'verbose_name_plural': 'Department Officials',
                'ordering': ['county_department__county__name', 'county_department__department__name', 'user__first_name'],
            },
        ),
    ]
